# Generated by Django 2.1.7 on 2019-03-24 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_by',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Modified by'),
        ),
    ]
