# Generated by Django 2.1.7 on 2019-03-24 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190324_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('created_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Created by')),
                ('modified_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Modified by')),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('created_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Created by')),
                ('modified_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Modified by')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('created_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Created by')),
                ('modified_by', models.IntegerField(default=0, editable=False, null=True, verbose_name='Modified by')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_hours', models.IntegerField()),
                ('expected_date', models.DateField()),
                ('incidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Incidence')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Priority')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Sprint')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.StatusTask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
