# Generated by Django 2.1.7 on 2019-05-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_incidence_priority_sprint_statustask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
